name: basmalla
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.5.1
  flutter: 
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0
  location: ^4.3.0
  shared_preferences: ^2.0.9
  card_settings: ^3.0.0
  geocoding: ^2.0.1
  font_awesome_flutter: ^9.2.0
  decorated_icon: ^1.2.1
  auto_size_text: ^3.0.0
  responsive_sizer: ^3.0.4+4
  dialogs: ^0.0.7

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter: 
  uses-material-design: true
  assets:
    - images/Masjid.jpg
    - assets/al_quran.json
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
fonts:
  - family: Oswald
    fonts:
      - asset: fonts/Oswald-Regular.ttf